apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github-webhook-receiver.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "github-webhook-receiver.labels" . | nindent 4 }}
type: Opaque
data:
  webhookSecret: {{ .Values.webhookSecret | b64enc | quote }}
